### ISSUE TITLE
Lua Debugger in test mode

### ISSUE THREAD

**Issue by knassar702** [BugBlocker/lotus#87]

**Comment by lenscas** [comment]
The debug library that lua has is disabled by default by mlua (and rlua for that matter) as it contains functions that can cause UB when used, keep this in mind when enabling it.

With that out of the way, you can probably just embed something like https://github.com/slembcke/debugger.lua once you enabled the debug library as it is just a single lua file.

Or... you can just enable the debug library when a flag is present and let people chose a debugger they want without officially supporting/preferring one.
